spring.application.name=SkinSense

server.port=${PORT:8080}

gemini.api.key=${GEMINI_API_KEY:}
gemini.model=${GEMINI_MODEL:gemini-2.5-flash}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models
gemini.timeout.seconds=45
